#!/bin/bash

echo "Variables globales:"
echo "USER: $USER"
echo "HOME: $HOME"
echo "PWD: $PWD"
echo "SHELL: $SHELL"

echo -e "\nArgumentos del Shell:"
echo "$@"

echo -e "\nValor retornado por el último comando ejecutado:"
echo "$?"

echo -e "\nPID de la Shell actual:"
echo "$$"
