#!/bin/bash

echo "Variables global:"
echo "USER: $USER"
echo "HOME: $HOME"
echo "PWD: $PWD"
echo "SHELL: $SHELL"

echo -e "\nArgumentos del Shell:"
echo "$@"

echo -e "\nValor Ultimo comando:"
echo "$?"

echo -e "\nPID:"
echo "$$"
